### ISSUE TITLE
Missing inverse functions for both algorithms.

### ISSUE THREAD

**Issue by FSharpCSharp** [robince/fst-uofc#1]
When using the library, I noticed that in the package and in the documentation it is mentioned that all algorithms have a inverse function. Unfortunately I don't find it anywhere in this package. Was it simply forgotten? It would be very good if there was still the possibility to get them.

Thank you very much!

**Comment by 0xBEEEF** [comment]
Interesting point. Also I couldn't find a way to invert the transformation within the package on the fly.  This applies to both 1D and 2D. I would also be in favour of adding the function here so that you can convert back changed signals and thus take advantage of the fast transformation.

**Comment by robince** [comment]
This is a fork of the main project at https://sourceforge.net/projects/fst-uofc/
I only added a Matlab wrapper (and made some other minor changes for my needs). 
For functionality of the C library I suggest you contact the developers of the original package.

**Comment by FSharpCSharp** [comment]
OK, I'm sorry about that. I thought that was the repository where the development took place.
