### ISSUE TITLE
Please add support for Python 3

### ISSUE THREAD

**Issue by 0xBEEEF** [robince/fst-uofc#2]
I wanted to test the project on a Python 3 development system. Unfortunately I didn't manage it. One of the problems is that you can't just install the code via the PIP. This would make the process much easier. Could you add support for Python 3 to the project? The old Python 2.X version is not available forever, and Python 3 has some advantages over Python 2.

**Comment by robince** [comment]
This is a fork of the main project at https://sourceforge.net/projects/fst-uofc/
I only added a Matlab wrapper (and made some other minor changes for my needs). 
For functionality of the C library and Python wrapper I suggest you contact the developers of the original package.

**Comment by 0xBEEEF** [comment]
All right, all right! I'm sorry, I didn't see that.
